// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: eventstore.proto

package bg.energo.eventstore.v1;

public interface AggregateOrBuilder extends
    // @@protoc_insertion_point(interface_extends:bg.energo.eventstore.v1.Aggregate)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string aggregateId = 1;</code>
   */
  java.lang.String getAggregateId();
  /**
   * <code>string aggregateId = 1;</code>
   */
  com.google.protobuf.ByteString
      getAggregateIdBytes();

  /**
   * <code>string aggregateType = 2;</code>
   */
  java.lang.String getAggregateType();
  /**
   * <code>string aggregateType = 2;</code>
   */
  com.google.protobuf.ByteString
      getAggregateTypeBytes();

  /**
   * <code>bytes snapshot = 3;</code>
   */
  com.google.protobuf.ByteString getSnapshot();

  /**
   * <code>int32 version = 4;</code>
   */
  int getVersion();

  /**
   * <code>repeated .bg.energo.eventstore.v1.EventPayload events = 5;</code>
   */
  java.util.List<bg.energo.eventstore.v1.EventPayload> 
      getEventsList();
  /**
   * <code>repeated .bg.energo.eventstore.v1.EventPayload events = 5;</code>
   */
  bg.energo.eventstore.v1.EventPayload getEvents(int index);
  /**
   * <code>repeated .bg.energo.eventstore.v1.EventPayload events = 5;</code>
   */
  int getEventsCount();
  /**
   * <code>repeated .bg.energo.eventstore.v1.EventPayload events = 5;</code>
   */
  java.util.List<? extends bg.energo.eventstore.v1.EventPayloadOrBuilder> 
      getEventsOrBuilderList();
  /**
   * <code>repeated .bg.energo.eventstore.v1.EventPayload events = 5;</code>
   */
  bg.energo.eventstore.v1.EventPayloadOrBuilder getEventsOrBuilder(
      int index);
}
