// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: eventstore.proto

package bg.energo.eventstore.v1;

public final class Eventstore {
  private Eventstore() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_bg_energo_eventstore_v1_SaveEventsRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_bg_energo_eventstore_v1_SaveEventsRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_bg_energo_eventstore_v1_SaveEventsResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_bg_energo_eventstore_v1_SaveEventsResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_bg_energo_eventstore_v1_GetAggregateEventsRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_bg_energo_eventstore_v1_GetAggregateEventsRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_bg_energo_eventstore_v1_GetAggregateEventsResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_bg_energo_eventstore_v1_GetAggregateEventsResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_bg_energo_eventstore_v1_Aggregate_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_bg_energo_eventstore_v1_Aggregate_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_bg_energo_eventstore_v1_EventPayload_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_bg_energo_eventstore_v1_EventPayload_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\020eventstore.proto\022\027bg.energo.eventstore" +
      ".v1\"\232\001\n\021SaveEventsRequest\022\023\n\013aggregateId" +
      "\030\001 \001(\t\022\025\n\raggregateType\030\002 \001(\t\022\017\n\007version" +
      "\030\003 \001(\005\0225\n\006events\030\004 \003(\0132%.bg.energo.event" +
      "store.v1.EventPayload\022\021\n\ttopicName\030\005 \001(\t" +
      "\":\n\022SaveEventsResponse\022\023\n\013aggregateId\030\001 " +
      "\001(\t\022\017\n\007version\030\002 \001(\005\"1\n\031GetAggregateEven" +
      "tsRequest\022\024\n\014aggregateIds\030\001 \003(\t\"T\n\032GetAg" +
      "gregateEventsResponse\0226\n\naggregates\030\001 \003(" +
      "\0132\".bg.energo.eventstore.v1.Aggregate\"\221\001" +
      "\n\tAggregate\022\023\n\013aggregateId\030\001 \001(\t\022\025\n\raggr" +
      "egateType\030\002 \001(\t\022\020\n\010snapshot\030\003 \001(\014\022\017\n\007ver" +
      "sion\030\004 \001(\005\0225\n\006events\030\005 \003(\0132%.bg.energo.e" +
      "ventstore.v1.EventPayload\"T\n\014EventPayloa" +
      "d\022\014\n\004kind\030\001 \001(\t\022\021\n\ttimestamp\030\002 \001(\004\022\022\n\nid" +
      "entityId\030\003 \001(\t\022\017\n\007payload\030\004 \001(\0142\202\002\n\021Even" +
      "tStoreService\022n\n\023SaveAggregateEvents\022*.b" +
      "g.energo.eventstore.v1.SaveEventsRequest" +
      "\032+.bg.energo.eventstore.v1.SaveEventsRes" +
      "ponse\022}\n\022getAggregateEvents\0222.bg.energo." +
      "eventstore.v1.GetAggregateEventsRequest\032" +
      "3.bg.energo.eventstore.v1.GetAggregateEv" +
      "entsResponseB\002P\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_bg_energo_eventstore_v1_SaveEventsRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_bg_energo_eventstore_v1_SaveEventsRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_bg_energo_eventstore_v1_SaveEventsRequest_descriptor,
        new java.lang.String[] { "AggregateId", "AggregateType", "Version", "Events", "TopicName", });
    internal_static_bg_energo_eventstore_v1_SaveEventsResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_bg_energo_eventstore_v1_SaveEventsResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_bg_energo_eventstore_v1_SaveEventsResponse_descriptor,
        new java.lang.String[] { "AggregateId", "Version", });
    internal_static_bg_energo_eventstore_v1_GetAggregateEventsRequest_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_bg_energo_eventstore_v1_GetAggregateEventsRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_bg_energo_eventstore_v1_GetAggregateEventsRequest_descriptor,
        new java.lang.String[] { "AggregateIds", });
    internal_static_bg_energo_eventstore_v1_GetAggregateEventsResponse_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_bg_energo_eventstore_v1_GetAggregateEventsResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_bg_energo_eventstore_v1_GetAggregateEventsResponse_descriptor,
        new java.lang.String[] { "Aggregates", });
    internal_static_bg_energo_eventstore_v1_Aggregate_descriptor =
      getDescriptor().getMessageTypes().get(4);
    internal_static_bg_energo_eventstore_v1_Aggregate_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_bg_energo_eventstore_v1_Aggregate_descriptor,
        new java.lang.String[] { "AggregateId", "AggregateType", "Snapshot", "Version", "Events", });
    internal_static_bg_energo_eventstore_v1_EventPayload_descriptor =
      getDescriptor().getMessageTypes().get(5);
    internal_static_bg_energo_eventstore_v1_EventPayload_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_bg_energo_eventstore_v1_EventPayload_descriptor,
        new java.lang.String[] { "Kind", "Timestamp", "IdentityId", "Payload", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
