// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: eventstore.proto

package bg.energo.eventstore.v1;

public final class Eventstore {
  private Eventstore() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_bg_energo_eventstore_v1_GetEventsRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_bg_energo_eventstore_v1_GetEventsRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_bg_energo_eventstore_v1_GetEventsResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_bg_energo_eventstore_v1_GetEventsResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\020eventstore.proto\022\027bg.energo.eventstore" +
      ".v1\"\'\n\020GetEventsRequest\022\023\n\013aggregateId\030\001" +
      " \001(\t\"(\n\021GetEventsResponse\022\023\n\013aggregateId" +
      "\030\001 \001(\t2w\n\021EventStoreService\022b\n\tgetEvents" +
      "\022).bg.energo.eventstore.v1.GetEventsRequ" +
      "est\032*.bg.energo.eventstore.v1.GetEventsR" +
      "esponseB\002P\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_bg_energo_eventstore_v1_GetEventsRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_bg_energo_eventstore_v1_GetEventsRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_bg_energo_eventstore_v1_GetEventsRequest_descriptor,
        new java.lang.String[] { "AggregateId", });
    internal_static_bg_energo_eventstore_v1_GetEventsResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_bg_energo_eventstore_v1_GetEventsResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_bg_energo_eventstore_v1_GetEventsResponse_descriptor,
        new java.lang.String[] { "AggregateId", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
