// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: eventstore.proto

package bg.energo.eventstore.v1;

/**
 * <pre>
 * The request containing list of aggregates to be retrieved.
 * </pre>
 *
 * Protobuf type {@code bg.energo.eventstore.v1.GetAggregateEventsRequest}
 */
public  final class GetAggregateEventsRequest extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:bg.energo.eventstore.v1.GetAggregateEventsRequest)
    GetAggregateEventsRequestOrBuilder {
private static final long serialVersionUID = 0L;
  // Use GetAggregateEventsRequest.newBuilder() to construct.
  private GetAggregateEventsRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private GetAggregateEventsRequest() {
    aggregateIds_ = com.google.protobuf.LazyStringArrayList.EMPTY;
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private GetAggregateEventsRequest(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          default: {
            if (!parseUnknownFieldProto3(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
          case 10: {
            java.lang.String s = input.readStringRequireUtf8();
            if (!((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
              aggregateIds_ = new com.google.protobuf.LazyStringArrayList();
              mutable_bitField0_ |= 0x00000001;
            }
            aggregateIds_.add(s);
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      if (((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
        aggregateIds_ = aggregateIds_.getUnmodifiableView();
      }
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return bg.energo.eventstore.v1.Eventstore.internal_static_bg_energo_eventstore_v1_GetAggregateEventsRequest_descriptor;
  }

  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return bg.energo.eventstore.v1.Eventstore.internal_static_bg_energo_eventstore_v1_GetAggregateEventsRequest_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            bg.energo.eventstore.v1.GetAggregateEventsRequest.class, bg.energo.eventstore.v1.GetAggregateEventsRequest.Builder.class);
  }

  public static final int AGGREGATEIDS_FIELD_NUMBER = 1;
  private com.google.protobuf.LazyStringList aggregateIds_;
  /**
   * <pre>
   * A list of aggregateIds which to be provided for the users
   * </pre>
   *
   * <code>repeated string aggregateIds = 1;</code>
   */
  public com.google.protobuf.ProtocolStringList
      getAggregateIdsList() {
    return aggregateIds_;
  }
  /**
   * <pre>
   * A list of aggregateIds which to be provided for the users
   * </pre>
   *
   * <code>repeated string aggregateIds = 1;</code>
   */
  public int getAggregateIdsCount() {
    return aggregateIds_.size();
  }
  /**
   * <pre>
   * A list of aggregateIds which to be provided for the users
   * </pre>
   *
   * <code>repeated string aggregateIds = 1;</code>
   */
  public java.lang.String getAggregateIds(int index) {
    return aggregateIds_.get(index);
  }
  /**
   * <pre>
   * A list of aggregateIds which to be provided for the users
   * </pre>
   *
   * <code>repeated string aggregateIds = 1;</code>
   */
  public com.google.protobuf.ByteString
      getAggregateIdsBytes(int index) {
    return aggregateIds_.getByteString(index);
  }

  private byte memoizedIsInitialized = -1;
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    for (int i = 0; i < aggregateIds_.size(); i++) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, aggregateIds_.getRaw(i));
    }
    unknownFields.writeTo(output);
  }

  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    {
      int dataSize = 0;
      for (int i = 0; i < aggregateIds_.size(); i++) {
        dataSize += computeStringSizeNoTag(aggregateIds_.getRaw(i));
      }
      size += dataSize;
      size += 1 * getAggregateIdsList().size();
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof bg.energo.eventstore.v1.GetAggregateEventsRequest)) {
      return super.equals(obj);
    }
    bg.energo.eventstore.v1.GetAggregateEventsRequest other = (bg.energo.eventstore.v1.GetAggregateEventsRequest) obj;

    boolean result = true;
    result = result && getAggregateIdsList()
        .equals(other.getAggregateIdsList());
    result = result && unknownFields.equals(other.unknownFields);
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (getAggregateIdsCount() > 0) {
      hash = (37 * hash) + AGGREGATEIDS_FIELD_NUMBER;
      hash = (53 * hash) + getAggregateIdsList().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static bg.energo.eventstore.v1.GetAggregateEventsRequest parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static bg.energo.eventstore.v1.GetAggregateEventsRequest parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static bg.energo.eventstore.v1.GetAggregateEventsRequest parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static bg.energo.eventstore.v1.GetAggregateEventsRequest parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static bg.energo.eventstore.v1.GetAggregateEventsRequest parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static bg.energo.eventstore.v1.GetAggregateEventsRequest parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static bg.energo.eventstore.v1.GetAggregateEventsRequest parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static bg.energo.eventstore.v1.GetAggregateEventsRequest parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static bg.energo.eventstore.v1.GetAggregateEventsRequest parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static bg.energo.eventstore.v1.GetAggregateEventsRequest parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static bg.energo.eventstore.v1.GetAggregateEventsRequest parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static bg.energo.eventstore.v1.GetAggregateEventsRequest parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(bg.energo.eventstore.v1.GetAggregateEventsRequest prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   * The request containing list of aggregates to be retrieved.
   * </pre>
   *
   * Protobuf type {@code bg.energo.eventstore.v1.GetAggregateEventsRequest}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:bg.energo.eventstore.v1.GetAggregateEventsRequest)
      bg.energo.eventstore.v1.GetAggregateEventsRequestOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return bg.energo.eventstore.v1.Eventstore.internal_static_bg_energo_eventstore_v1_GetAggregateEventsRequest_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return bg.energo.eventstore.v1.Eventstore.internal_static_bg_energo_eventstore_v1_GetAggregateEventsRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              bg.energo.eventstore.v1.GetAggregateEventsRequest.class, bg.energo.eventstore.v1.GetAggregateEventsRequest.Builder.class);
    }

    // Construct using bg.energo.eventstore.v1.GetAggregateEventsRequest.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    public Builder clear() {
      super.clear();
      aggregateIds_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      bitField0_ = (bitField0_ & ~0x00000001);
      return this;
    }

    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return bg.energo.eventstore.v1.Eventstore.internal_static_bg_energo_eventstore_v1_GetAggregateEventsRequest_descriptor;
    }

    public bg.energo.eventstore.v1.GetAggregateEventsRequest getDefaultInstanceForType() {
      return bg.energo.eventstore.v1.GetAggregateEventsRequest.getDefaultInstance();
    }

    public bg.energo.eventstore.v1.GetAggregateEventsRequest build() {
      bg.energo.eventstore.v1.GetAggregateEventsRequest result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    public bg.energo.eventstore.v1.GetAggregateEventsRequest buildPartial() {
      bg.energo.eventstore.v1.GetAggregateEventsRequest result = new bg.energo.eventstore.v1.GetAggregateEventsRequest(this);
      int from_bitField0_ = bitField0_;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        aggregateIds_ = aggregateIds_.getUnmodifiableView();
        bitField0_ = (bitField0_ & ~0x00000001);
      }
      result.aggregateIds_ = aggregateIds_;
      onBuilt();
      return result;
    }

    public Builder clone() {
      return (Builder) super.clone();
    }
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.setField(field, value);
    }
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof bg.energo.eventstore.v1.GetAggregateEventsRequest) {
        return mergeFrom((bg.energo.eventstore.v1.GetAggregateEventsRequest)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(bg.energo.eventstore.v1.GetAggregateEventsRequest other) {
      if (other == bg.energo.eventstore.v1.GetAggregateEventsRequest.getDefaultInstance()) return this;
      if (!other.aggregateIds_.isEmpty()) {
        if (aggregateIds_.isEmpty()) {
          aggregateIds_ = other.aggregateIds_;
          bitField0_ = (bitField0_ & ~0x00000001);
        } else {
          ensureAggregateIdsIsMutable();
          aggregateIds_.addAll(other.aggregateIds_);
        }
        onChanged();
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    public final boolean isInitialized() {
      return true;
    }

    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      bg.energo.eventstore.v1.GetAggregateEventsRequest parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (bg.energo.eventstore.v1.GetAggregateEventsRequest) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private com.google.protobuf.LazyStringList aggregateIds_ = com.google.protobuf.LazyStringArrayList.EMPTY;
    private void ensureAggregateIdsIsMutable() {
      if (!((bitField0_ & 0x00000001) == 0x00000001)) {
        aggregateIds_ = new com.google.protobuf.LazyStringArrayList(aggregateIds_);
        bitField0_ |= 0x00000001;
       }
    }
    /**
     * <pre>
     * A list of aggregateIds which to be provided for the users
     * </pre>
     *
     * <code>repeated string aggregateIds = 1;</code>
     */
    public com.google.protobuf.ProtocolStringList
        getAggregateIdsList() {
      return aggregateIds_.getUnmodifiableView();
    }
    /**
     * <pre>
     * A list of aggregateIds which to be provided for the users
     * </pre>
     *
     * <code>repeated string aggregateIds = 1;</code>
     */
    public int getAggregateIdsCount() {
      return aggregateIds_.size();
    }
    /**
     * <pre>
     * A list of aggregateIds which to be provided for the users
     * </pre>
     *
     * <code>repeated string aggregateIds = 1;</code>
     */
    public java.lang.String getAggregateIds(int index) {
      return aggregateIds_.get(index);
    }
    /**
     * <pre>
     * A list of aggregateIds which to be provided for the users
     * </pre>
     *
     * <code>repeated string aggregateIds = 1;</code>
     */
    public com.google.protobuf.ByteString
        getAggregateIdsBytes(int index) {
      return aggregateIds_.getByteString(index);
    }
    /**
     * <pre>
     * A list of aggregateIds which to be provided for the users
     * </pre>
     *
     * <code>repeated string aggregateIds = 1;</code>
     */
    public Builder setAggregateIds(
        int index, java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  ensureAggregateIdsIsMutable();
      aggregateIds_.set(index, value);
      onChanged();
      return this;
    }
    /**
     * <pre>
     * A list of aggregateIds which to be provided for the users
     * </pre>
     *
     * <code>repeated string aggregateIds = 1;</code>
     */
    public Builder addAggregateIds(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  ensureAggregateIdsIsMutable();
      aggregateIds_.add(value);
      onChanged();
      return this;
    }
    /**
     * <pre>
     * A list of aggregateIds which to be provided for the users
     * </pre>
     *
     * <code>repeated string aggregateIds = 1;</code>
     */
    public Builder addAllAggregateIds(
        java.lang.Iterable<java.lang.String> values) {
      ensureAggregateIdsIsMutable();
      com.google.protobuf.AbstractMessageLite.Builder.addAll(
          values, aggregateIds_);
      onChanged();
      return this;
    }
    /**
     * <pre>
     * A list of aggregateIds which to be provided for the users
     * </pre>
     *
     * <code>repeated string aggregateIds = 1;</code>
     */
    public Builder clearAggregateIds() {
      aggregateIds_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      bitField0_ = (bitField0_ & ~0x00000001);
      onChanged();
      return this;
    }
    /**
     * <pre>
     * A list of aggregateIds which to be provided for the users
     * </pre>
     *
     * <code>repeated string aggregateIds = 1;</code>
     */
    public Builder addAggregateIdsBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      ensureAggregateIdsIsMutable();
      aggregateIds_.add(value);
      onChanged();
      return this;
    }
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFieldsProto3(unknownFields);
    }

    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:bg.energo.eventstore.v1.GetAggregateEventsRequest)
  }

  // @@protoc_insertion_point(class_scope:bg.energo.eventstore.v1.GetAggregateEventsRequest)
  private static final bg.energo.eventstore.v1.GetAggregateEventsRequest DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new bg.energo.eventstore.v1.GetAggregateEventsRequest();
  }

  public static bg.energo.eventstore.v1.GetAggregateEventsRequest getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<GetAggregateEventsRequest>
      PARSER = new com.google.protobuf.AbstractParser<GetAggregateEventsRequest>() {
    public GetAggregateEventsRequest parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new GetAggregateEventsRequest(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<GetAggregateEventsRequest> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<GetAggregateEventsRequest> getParserForType() {
    return PARSER;
  }

  public bg.energo.eventstore.v1.GetAggregateEventsRequest getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

