// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: eventstore.proto

package bg.energo.eventstore.v1;

public interface GetAggregateEventsRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:bg.energo.eventstore.v1.GetAggregateEventsRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * A list of aggregateIds which to be provided for the users
   * </pre>
   *
   * <code>repeated string aggregateIds = 1;</code>
   */
  java.util.List<java.lang.String>
      getAggregateIdsList();
  /**
   * <pre>
   * A list of aggregateIds which to be provided for the users
   * </pre>
   *
   * <code>repeated string aggregateIds = 1;</code>
   */
  int getAggregateIdsCount();
  /**
   * <pre>
   * A list of aggregateIds which to be provided for the users
   * </pre>
   *
   * <code>repeated string aggregateIds = 1;</code>
   */
  java.lang.String getAggregateIds(int index);
  /**
   * <pre>
   * A list of aggregateIds which to be provided for the users
   * </pre>
   *
   * <code>repeated string aggregateIds = 1;</code>
   */
  com.google.protobuf.ByteString
      getAggregateIdsBytes(int index);
}
