// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: eventstore.proto

package bg.energo.eventstore.v1;

public interface GetEventsResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:bg.energo.eventstore.v1.GetEventsResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string aggregateId = 1;</code>
   */
  java.lang.String getAggregateId();
  /**
   * <code>string aggregateId = 1;</code>
   */
  com.google.protobuf.ByteString
      getAggregateIdBytes();
}
