// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: eventstore.proto

package bg.energo.eventstore.v1;

public interface SaveEventsRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:bg.energo.eventstore.v1.SaveEventsRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * The id of the aggregate
   * </pre>
   *
   * <code>string aggregateId = 1;</code>
   */
  java.lang.String getAggregateId();
  /**
   * <pre>
   * The id of the aggregate
   * </pre>
   *
   * <code>string aggregateId = 1;</code>
   */
  com.google.protobuf.ByteString
      getAggregateIdBytes();

  /**
   * <pre>
   * The type of the aggregate, e.g Order, Invoice and etc.
   * </pre>
   *
   * <code>string aggregateType = 2;</code>
   */
  java.lang.String getAggregateType();
  /**
   * <pre>
   * The type of the aggregate, e.g Order, Invoice and etc.
   * </pre>
   *
   * <code>string aggregateType = 2;</code>
   */
  com.google.protobuf.ByteString
      getAggregateTypeBytes();

  /**
   * <pre>
   * Used to perform a consistent read-modify-write.
   * </pre>
   *
   * <code>int32 version = 3;</code>
   */
  int getVersion();

  /**
   * <pre>
   * List of events associated with aggregate.
   * </pre>
   *
   * <code>repeated .bg.energo.eventstore.v1.EventPayload events = 4;</code>
   */
  java.util.List<bg.energo.eventstore.v1.EventPayload> 
      getEventsList();
  /**
   * <pre>
   * List of events associated with aggregate.
   * </pre>
   *
   * <code>repeated .bg.energo.eventstore.v1.EventPayload events = 4;</code>
   */
  bg.energo.eventstore.v1.EventPayload getEvents(int index);
  /**
   * <pre>
   * List of events associated with aggregate.
   * </pre>
   *
   * <code>repeated .bg.energo.eventstore.v1.EventPayload events = 4;</code>
   */
  int getEventsCount();
  /**
   * <pre>
   * List of events associated with aggregate.
   * </pre>
   *
   * <code>repeated .bg.energo.eventstore.v1.EventPayload events = 4;</code>
   */
  java.util.List<? extends bg.energo.eventstore.v1.EventPayloadOrBuilder> 
      getEventsOrBuilderList();
  /**
   * <pre>
   * List of events associated with aggregate.
   * </pre>
   *
   * <code>repeated .bg.energo.eventstore.v1.EventPayload events = 4;</code>
   */
  bg.energo.eventstore.v1.EventPayloadOrBuilder getEventsOrBuilder(
      int index);

  /**
   * <pre>
   * The name of the topic to which the events to be published.
   * </pre>
   *
   * <code>string topicName = 5;</code>
   */
  java.lang.String getTopicName();
  /**
   * <pre>
   * The name of the topic to which the events to be published.
   * </pre>
   *
   * <code>string topicName = 5;</code>
   */
  com.google.protobuf.ByteString
      getTopicNameBytes();
}
