// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: eventstore.proto

package bg.energo.eventstore.v1;

/**
 * <pre>
 * The response containing the Id of the aggregate and the next version.
 * </pre>
 *
 * Protobuf type {@code bg.energo.eventstore.v1.SaveEventsResponse}
 */
public  final class SaveEventsResponse extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:bg.energo.eventstore.v1.SaveEventsResponse)
    SaveEventsResponseOrBuilder {
private static final long serialVersionUID = 0L;
  // Use SaveEventsResponse.newBuilder() to construct.
  private SaveEventsResponse(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private SaveEventsResponse() {
    aggregateId_ = "";
    version_ = 0;
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private SaveEventsResponse(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          default: {
            if (!parseUnknownFieldProto3(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
          case 10: {
            java.lang.String s = input.readStringRequireUtf8();

            aggregateId_ = s;
            break;
          }
          case 16: {

            version_ = input.readInt32();
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return bg.energo.eventstore.v1.Eventstore.internal_static_bg_energo_eventstore_v1_SaveEventsResponse_descriptor;
  }

  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return bg.energo.eventstore.v1.Eventstore.internal_static_bg_energo_eventstore_v1_SaveEventsResponse_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            bg.energo.eventstore.v1.SaveEventsResponse.class, bg.energo.eventstore.v1.SaveEventsResponse.Builder.class);
  }

  public static final int AGGREGATEID_FIELD_NUMBER = 1;
  private volatile java.lang.Object aggregateId_;
  /**
   * <pre>
   * The id of the aggregate
   * </pre>
   *
   * <code>string aggregateId = 1;</code>
   */
  public java.lang.String getAggregateId() {
    java.lang.Object ref = aggregateId_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      aggregateId_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * The id of the aggregate
   * </pre>
   *
   * <code>string aggregateId = 1;</code>
   */
  public com.google.protobuf.ByteString
      getAggregateIdBytes() {
    java.lang.Object ref = aggregateId_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      aggregateId_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int VERSION_FIELD_NUMBER = 2;
  private int version_;
  /**
   * <pre>
   * Used to perform a consistent read-modify-write.
   * </pre>
   *
   * <code>int32 version = 2;</code>
   */
  public int getVersion() {
    return version_;
  }

  private byte memoizedIsInitialized = -1;
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!getAggregateIdBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, aggregateId_);
    }
    if (version_ != 0) {
      output.writeInt32(2, version_);
    }
    unknownFields.writeTo(output);
  }

  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!getAggregateIdBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, aggregateId_);
    }
    if (version_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(2, version_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof bg.energo.eventstore.v1.SaveEventsResponse)) {
      return super.equals(obj);
    }
    bg.energo.eventstore.v1.SaveEventsResponse other = (bg.energo.eventstore.v1.SaveEventsResponse) obj;

    boolean result = true;
    result = result && getAggregateId()
        .equals(other.getAggregateId());
    result = result && (getVersion()
        == other.getVersion());
    result = result && unknownFields.equals(other.unknownFields);
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + AGGREGATEID_FIELD_NUMBER;
    hash = (53 * hash) + getAggregateId().hashCode();
    hash = (37 * hash) + VERSION_FIELD_NUMBER;
    hash = (53 * hash) + getVersion();
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static bg.energo.eventstore.v1.SaveEventsResponse parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static bg.energo.eventstore.v1.SaveEventsResponse parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static bg.energo.eventstore.v1.SaveEventsResponse parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static bg.energo.eventstore.v1.SaveEventsResponse parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static bg.energo.eventstore.v1.SaveEventsResponse parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static bg.energo.eventstore.v1.SaveEventsResponse parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static bg.energo.eventstore.v1.SaveEventsResponse parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static bg.energo.eventstore.v1.SaveEventsResponse parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static bg.energo.eventstore.v1.SaveEventsResponse parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static bg.energo.eventstore.v1.SaveEventsResponse parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static bg.energo.eventstore.v1.SaveEventsResponse parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static bg.energo.eventstore.v1.SaveEventsResponse parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(bg.energo.eventstore.v1.SaveEventsResponse prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   * The response containing the Id of the aggregate and the next version.
   * </pre>
   *
   * Protobuf type {@code bg.energo.eventstore.v1.SaveEventsResponse}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:bg.energo.eventstore.v1.SaveEventsResponse)
      bg.energo.eventstore.v1.SaveEventsResponseOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return bg.energo.eventstore.v1.Eventstore.internal_static_bg_energo_eventstore_v1_SaveEventsResponse_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return bg.energo.eventstore.v1.Eventstore.internal_static_bg_energo_eventstore_v1_SaveEventsResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              bg.energo.eventstore.v1.SaveEventsResponse.class, bg.energo.eventstore.v1.SaveEventsResponse.Builder.class);
    }

    // Construct using bg.energo.eventstore.v1.SaveEventsResponse.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    public Builder clear() {
      super.clear();
      aggregateId_ = "";

      version_ = 0;

      return this;
    }

    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return bg.energo.eventstore.v1.Eventstore.internal_static_bg_energo_eventstore_v1_SaveEventsResponse_descriptor;
    }

    public bg.energo.eventstore.v1.SaveEventsResponse getDefaultInstanceForType() {
      return bg.energo.eventstore.v1.SaveEventsResponse.getDefaultInstance();
    }

    public bg.energo.eventstore.v1.SaveEventsResponse build() {
      bg.energo.eventstore.v1.SaveEventsResponse result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    public bg.energo.eventstore.v1.SaveEventsResponse buildPartial() {
      bg.energo.eventstore.v1.SaveEventsResponse result = new bg.energo.eventstore.v1.SaveEventsResponse(this);
      result.aggregateId_ = aggregateId_;
      result.version_ = version_;
      onBuilt();
      return result;
    }

    public Builder clone() {
      return (Builder) super.clone();
    }
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.setField(field, value);
    }
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof bg.energo.eventstore.v1.SaveEventsResponse) {
        return mergeFrom((bg.energo.eventstore.v1.SaveEventsResponse)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(bg.energo.eventstore.v1.SaveEventsResponse other) {
      if (other == bg.energo.eventstore.v1.SaveEventsResponse.getDefaultInstance()) return this;
      if (!other.getAggregateId().isEmpty()) {
        aggregateId_ = other.aggregateId_;
        onChanged();
      }
      if (other.getVersion() != 0) {
        setVersion(other.getVersion());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    public final boolean isInitialized() {
      return true;
    }

    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      bg.energo.eventstore.v1.SaveEventsResponse parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (bg.energo.eventstore.v1.SaveEventsResponse) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private java.lang.Object aggregateId_ = "";
    /**
     * <pre>
     * The id of the aggregate
     * </pre>
     *
     * <code>string aggregateId = 1;</code>
     */
    public java.lang.String getAggregateId() {
      java.lang.Object ref = aggregateId_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        aggregateId_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * The id of the aggregate
     * </pre>
     *
     * <code>string aggregateId = 1;</code>
     */
    public com.google.protobuf.ByteString
        getAggregateIdBytes() {
      java.lang.Object ref = aggregateId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        aggregateId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * The id of the aggregate
     * </pre>
     *
     * <code>string aggregateId = 1;</code>
     */
    public Builder setAggregateId(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      aggregateId_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * The id of the aggregate
     * </pre>
     *
     * <code>string aggregateId = 1;</code>
     */
    public Builder clearAggregateId() {
      
      aggregateId_ = getDefaultInstance().getAggregateId();
      onChanged();
      return this;
    }
    /**
     * <pre>
     * The id of the aggregate
     * </pre>
     *
     * <code>string aggregateId = 1;</code>
     */
    public Builder setAggregateIdBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      aggregateId_ = value;
      onChanged();
      return this;
    }

    private int version_ ;
    /**
     * <pre>
     * Used to perform a consistent read-modify-write.
     * </pre>
     *
     * <code>int32 version = 2;</code>
     */
    public int getVersion() {
      return version_;
    }
    /**
     * <pre>
     * Used to perform a consistent read-modify-write.
     * </pre>
     *
     * <code>int32 version = 2;</code>
     */
    public Builder setVersion(int value) {
      
      version_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Used to perform a consistent read-modify-write.
     * </pre>
     *
     * <code>int32 version = 2;</code>
     */
    public Builder clearVersion() {
      
      version_ = 0;
      onChanged();
      return this;
    }
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFieldsProto3(unknownFields);
    }

    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:bg.energo.eventstore.v1.SaveEventsResponse)
  }

  // @@protoc_insertion_point(class_scope:bg.energo.eventstore.v1.SaveEventsResponse)
  private static final bg.energo.eventstore.v1.SaveEventsResponse DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new bg.energo.eventstore.v1.SaveEventsResponse();
  }

  public static bg.energo.eventstore.v1.SaveEventsResponse getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<SaveEventsResponse>
      PARSER = new com.google.protobuf.AbstractParser<SaveEventsResponse>() {
    public SaveEventsResponse parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new SaveEventsResponse(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<SaveEventsResponse> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<SaveEventsResponse> getParserForType() {
    return PARSER;
  }

  public bg.energo.eventstore.v1.SaveEventsResponse getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

